# Generated by Django 5.0.6 on 2024-07-21 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=64)),
                ("email", models.CharField(max_length=128)),
                ("address", models.CharField(default="", max_length=250)),
                ("city", models.CharField(default="", max_length=32)),
                ("phone", models.CharField(default="", max_length=16)),
                ("country", models.CharField(default="", max_length=32)),
                ("index", models.CharField(default="", max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
        migrations.AddField(
            model_name="order",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_info",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.shippinginfo",
            ),
        ),
    ]
